### ISSUE TITLE
USF-course compiler at GitHub

### ISSUE THREAD

**Issue by cagryInside** [erodrig9/DJ-Compiler#1]
Hello @erodrig9. I'm the TA for Dr. Ligatti's compilers course this year.  He asked me to contact you and request that you remove your compiler-assignment solutions from public view.  Students may use this code to implement their compiler. This would considered as cheating.  Already this semester we caught 4 students in the compilers course using old solutions posted on Github. Please consider removing your solutions from GitHub.

**Comment by erodrig9** [comment]
@cagryInside I will be taking it down.  Thanks!
